# This file was generated by GoReleaser. DO NOT EDIT.
cask "clasing-skill" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "17f30ca65bed7c624f2a11a2fcf1430b9b6466583b62eb911203378066cffef4"
      url "https://github.com/joeldevz/skills/releases/download/v#{version}/clasing-skill_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c7dd356b4b8763ad64aea842bb1b22e71a21731c8189ceb99870467c3bc2510"
      url "https://github.com/joeldevz/skills/releases/download/v#{version}/clasing-skill_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6568b68bb740a4028d982e4e8863793a85493d6f45bd721ccfd978ae3a4b53b2"
      url "https://github.com/joeldevz/skills/releases/download/v#{version}/clasing-skill_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "864a3aaa4d7afeab32d23aa35c2894fe1d0e9756e7525ce59399b5de94a71d8c"
      url "https://github.com/joeldevz/skills/releases/download/v#{version}/clasing-skill_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clasing-skill"
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clasing-skill"

  # No zap stanza required

end
