# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClasingSkill < Formula
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skills"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeldevz/skills/releases/download/v1.0.0/clasing-skill_1.0.0_darwin_amd64.tar.gz"
      sha256 "daac834d7745e68294ddf0c84e61a89fa7124c91e600967ba400de8ae4e10edd"

      def install
        bin.install "clasing-skill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeldevz/skills/releases/download/v1.0.0/clasing-skill_1.0.0_darwin_arm64.tar.gz"
      sha256 "e90e151e0e25cddcfe7a250ef100a7df51ace93f3239954ec2c549e467b2dd6a"

      def install
        bin.install "clasing-skill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skills/releases/download/v1.0.0/clasing-skill_1.0.0_linux_amd64.tar.gz"
      sha256 "f396fca0702d41b006a67bd13d47f02bd084ceb4e1cb53dabf9fb4bf5a4a715a"

      def install
        bin.install "clasing-skill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skills/releases/download/v1.0.0/clasing-skill_1.0.0_linux_arm64.tar.gz"
      sha256 "a8771b357843979e000c41b6989d1973accc8d46ea5be4ac86dd192ba140a8f2"

      def install
        bin.install "clasing-skill"
      end
    end
  end

  test do
    system "#{bin}/clasing-skill", "--version"
  end
end
