# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skilar < Formula
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skilar"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.7/skilar_1.0.7_darwin_amd64.tar.gz"
      sha256 "4af7581c9180164010fae03869d5727b3c328e85f58fddc0a886e8c8423b3627"

      define_method(:install) do
        bin.install "skilar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.7/skilar_1.0.7_darwin_arm64.tar.gz"
      sha256 "4f112aa2d2711a088f4c4655e256301a3f1d92129a39b8a2a7b141f04a8a5a8d"

      define_method(:install) do
        bin.install "skilar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.7/skilar_1.0.7_linux_amd64.tar.gz"
      sha256 "1fc773f4c270f5bbb960ce2f1f43b87980757461a4efd0355003dae8fd9a7154"
      define_method(:install) do
        bin.install "skilar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.7/skilar_1.0.7_linux_arm64.tar.gz"
      sha256 "2909ae187dd76ad3c216a53229e85219e61fadc30fc8ade9dff2b8b931610ae9"
      define_method(:install) do
        bin.install "skilar"
      end
    end
  end

  test do
    system "#{bin}/skilar", "--version"
  end
end
