# This file was generated by GoReleaser. DO NOT EDIT.
cask "skilar" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "a1b63051dcf729188ac78a9ac3da869f6adbc159eda3b700153c82a926724b52"
      url "https://github.com/joeldevz/skilar/releases/download/v#{version}/skilar_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "74e5978718dd503c8615bc530c0f391d08659b3c757e095359f5bf40d220e6bf"
      url "https://github.com/joeldevz/skilar/releases/download/v#{version}/skilar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a9b3cf5be17b94a89ca5efacd06071da0057e717ca3d9189f45d49d772a2787"
      url "https://github.com/joeldevz/skilar/releases/download/v#{version}/skilar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c742c0ddf2b5becd6f60e69e35c0794c1951d325c7e39dcbf2c076f7ba95c1b"
      url "https://github.com/joeldevz/skilar/releases/download/v#{version}/skilar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skilar"
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skilar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skilar"

  # No zap stanza required

end
