# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skilar < Formula
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skilar"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.4/skilar_1.0.4_darwin_amd64.tar.gz"
      sha256 "3223670c69980ac930753b383f06b6017bc12492ce285b69682b2949f94dad8d"

      define_method(:install) do
        bin.install "skilar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.4/skilar_1.0.4_darwin_arm64.tar.gz"
      sha256 "4b19c846a375733ed605b31e10e979e3ba2b46ad663bb19189e6ed2684e1c6cf"

      define_method(:install) do
        bin.install "skilar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.4/skilar_1.0.4_linux_amd64.tar.gz"
      sha256 "5da2c1729c5d086016bceb3e2be2081ea5f3ced74781b1ed2dfc51d4ef23ca12"
      define_method(:install) do
        bin.install "skilar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skilar/releases/download/v1.0.4/skilar_1.0.4_linux_arm64.tar.gz"
      sha256 "67756b324c4aec9215f75f9d9cf887530b71a6efc2ffdc3be7226d92af519907"
      define_method(:install) do
        bin.install "skilar"
      end
    end
  end

  test do
    system "#{bin}/skilar", "--version"
  end
end
