# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skynex < Formula
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skynex"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeldevz/skynex/releases/download/v1.6.0/skynex_1.6.0_darwin_amd64.tar.gz"
      sha256 "8fc9f96fd296141eab7300c2252253894d772be1f3fc26ca571cc0180c758217"

      define_method(:install) do
        bin.install "skynex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeldevz/skynex/releases/download/v1.6.0/skynex_1.6.0_darwin_arm64.tar.gz"
      sha256 "4ea64c24079df9c7729339c69a3a6b091cdde081ed14240f8af568de0c85b4d1"

      define_method(:install) do
        bin.install "skynex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skynex/releases/download/v1.6.0/skynex_1.6.0_linux_amd64.tar.gz"
      sha256 "7b0563c0b8681743459374b9da55c644f3b4311787aac51d5a4543eed0a50b44"
      define_method(:install) do
        bin.install "skynex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joeldevz/skynex/releases/download/v1.6.0/skynex_1.6.0_linux_arm64.tar.gz"
      sha256 "e4211dd6b8ba5aa89ddd0f40f79f8f6f4a6945fd87737328fe03b635509bd627"
      define_method(:install) do
        bin.install "skynex"
      end
    end
  end

  test do
    system "#{bin}/skynex", "--version"
  end
end
