# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skynex < Formula
  desc "AI agent skills installer for OpenCode and Claude Code"
  homepage "https://github.com/joeldevz/skynex"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joeldevz/skynex/releases/download/v2.0.0/skynex_2.0.0_darwin_amd64.tar.gz"
      sha256 "cf11d6f9e19b7d35d788dea87a192febcd25902dd297d3dc24fdd507cab5ebdb"

      def install
        bin.install "skynex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joeldevz/skynex/releases/download/v2.0.0/skynex_2.0.0_darwin_arm64.tar.gz"
      sha256 "990fb24cbf47fb7f5b1aab078103bf3e1180b12c8da9736d0b2f405d60dc3ccd"

      def install
        bin.install "skynex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joeldevz/skynex/releases/download/v2.0.0/skynex_2.0.0_linux_amd64.tar.gz"
        sha256 "19fb652734db60cb9e32d6412d5132739145712e7de1678b09f8dcba21d35779"

        def install
          bin.install "skynex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joeldevz/skynex/releases/download/v2.0.0/skynex_2.0.0_linux_arm64.tar.gz"
        sha256 "89b6b89b2515d4ff043dcd9b8f52f7e68bad936e56b0876ae5338b4ac6fe3783"

        def install
          bin.install "skynex"
        end
      end
    end
  end

  test do
    system "#{bin}/skynex", "--version"
  end
end
